sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

  alioss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5tKDhrXgLPPaYexPdbBH
      access-key-secret: EL46i29RNmZTk4yC5Y0BdynzxOk7Vq
      bucket-name: sky-dsy
  redis:
    host: localhost
    port: 6379
    password: 123456
  wechat:
    appid: wx6cf5498c2fbe10c1
    secret: f4583b30fd0d0828a962001304b34149